version: 2
updates:
  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "dependency updates"
